n_runs: 1
experiment: "bci-competition-IV2b"
data_dir: "../Datasets/BCICompetition-IV2b/"  ##### ~ replace with your own data path
dataset_name: "BCICompIV2b"
checkpoint: "./checkpoints/"
approach: 'ca4mi'
output: ""

orth: "yes"
pro_loss_reg: 0.02

lam: 1
adv: 0.05
orth_reg: 0.1
seed: 0
alpha: 0.5

n_times: 750
n_chans: 3
n_subjects:  9
n_classes: 2

use_memory: "yes"
n_samples: 50
global_reservoir_size : 500

use_prototypes: 'yes'
max_prototypes: 40
align: 'yes'
mixup: 'yes'

#### Encoder
encoder_lr: 0.0005
encoder_wd: 0.03
shared_step: 2

#### Discriminator
discriminator_lr: 0.0005
discriminator_wd: 0.03
discriminator_step: 1


lr_factor: 3
lr_min: 1.0e-06
lr_patience: 6
mom: 0.9

inputsize: [724, 3, 750]
model: 'DCN'     # 'SCN', 'EEGNet'
latent_dim: 128
hidden_dim: [64, 32]
dropout: 0.25
n_layers: 3

batch_size: 32
n_epochs: 200
pc_valid: 0.15
pc_test: 0.15

n_workers: 1
device: "cuda:0"